version: '3'

services:
  api_db:
    image: mongo:latest
    container_name: muzic-api-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_api:/data/db
    networks:
      - muzic-network

volumes:
  mongodb_api:
#   nginx:
#     image: nginx:stable-alpine
#     container_name: muzic-nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
#     depends_on:
#       - frontend
#       - api
#     networks:
#       - muzic-network

# volumes:
#   mongodb_api:

# networks:
#   muzic-network:
#     driver: bridge

